language: minimal
services:
  - docker
env:
  matrix:
    - GO_VERSION=1.10 PG_MAJOR=9.6
    - GO_VERSION=1.10 PG_MAJOR=10
    - GO_VERSION=1.10 PG_MAJOR=11
    - GO_VERSION=1.11 PG_MAJOR=9.6
    - GO_VERSION=1.11 PG_MAJOR=10
    - GO_VERSION=1.11 PG_MAJOR=11
matrix:
  allow_failures:
    - env: GO_VERSION=1.10 PG_MAJOR=11
    - env: GO_VERSION=1.11 PG_MAJOR=11
before_script:
  - make build-check
script:
  - make check
